chore: adding git hooks
atlp-rwanda/e-comm-team-axel25-fe pull request #13
Opened 2023-03-23 18:27 UTC by ISHIMWE-Aime

# Description
I have added pre-commit and pre-push git hooks.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-25 17:17 UTC, mucyoalexaxel requested changes
@emilenfc check the suggested changes.

2023-03-25 17:17 UTC, mucyoalexaxel commented on .husky/pre-commit
> +npm test
```suggestion
pnpm test
```

2023-03-26 10:46 UTC, emilenfc submitted a review, later dismissed
LGTM

2023-03-26 11:21 UTC, emilenfc approved these changes
LGTM

2023-03-26 12:05 UTC, mucyoalexaxel approved these changes
LGTM

2023-03-26 12:06 UTC, merged