ft: add star ratings component [#44]
atlp-rwanda/e-comm-team-axel25-fe pull request #45
Opened 2023-04-03 11:44 UTC by SergeInGithub

# Description

This will add the following component:
- Product ratings star

Fixes # (issue)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-03 13:29 UTC, musllim requested changes
remove the shadow on stars container

2023-04-03 19:40 UTC, mucyoalexaxel requested changes
@SergeInGithub Great work on this PR, check the suggested changes below.

2023-04-03 19:40 UTC, mucyoalexaxel commented on src/components/ui/Stars.tsx
> +/* eslint-disable react/require-default-props */
```suggestion
```
fix this es-lint errors.

2023-04-03 19:40 UTC, mucyoalexaxel commented on src/components/ui/index.ts
@SergeInGithub rename the `ui` folder to `shared`

2023-04-03 21:03 UTC, shyakadavis approved these changes
LGTM

2023-04-04 08:56 UTC, emilenfc approved these changes
LGTM

2023-04-04 09:11 UTC, musllim approved these changes
Looks good

2023-04-04 13:52 UTC, mucyoalexaxel approved these changes
@SergeInGithub great work here

2023-04-04 13:54 UTC, merged