ft: add categories ui & sidebar 🗳️
atlp-rwanda/e-comm-team-axel25-fe pull request #48
Opened 2023-04-06 17:15 UTC by shyakadavis

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-11 17:26 UTC, SergeInGithub reviewed
Nice work here.
Quick suggestion, i think you could reduce the height of either the navbar or the subheader because it think it's taking a little too much of upper screen space.

💡 Maybe we can reduce the space between the two, or even the height of the search input, etc...

Do you think so too? @shyakadavis

2023-04-11 18:49 UTC, shyakadavis commented
> Nice work here. Quick suggestion, i think you could reduce the height of either the navbar or the subheader because it think it's taking a little too much of upper screen space.
> 
> 💡 Maybe we can reduce the space between the two, or even the height of the search input, etc...
> 
> Do you think so too? @shyakadavis

Let me see what I can do.

2023-04-12 15:35 UTC, SergeInGithub approved these changes
LGTM

2023-04-13 06:15 UTC, ISHIMWE-Aime commented
Good morning @shyakadavis , as Serge mentioned I have seen that :
1. In small mobile screens that category ui and header containing searching component they are taking a lot of space; they are too large w.r.t screen size. 
2. Also on side bar, from my point of view I don't think if is necessary to add those icons located next to searching component to the header of sidebar, as the user he/she will click on sidebar icon to look for something new. I think is like duplicating things. 
As usually, if I am wrong, please remember I am willing to hear from you. 
Apart from that, you've done great work.

2023-04-13 07:49 UTC, shyakadavis commented
> Details

1. The issue with the size was resolved. If there is something specific about that, please send me a screenshot, or head over to chromatic and point it out.

2. That is just placeholder content. I just didn't want to leave it blank.

2023-04-13 07:49 UTC, shyakadavis commented
> Good morning @shyakadavis , as Serge mentioned I have seen that :
> 
> 1. In small mobile screens that category ui and header containing searching component they are taking a lot of space; they are too large w.r.t screen size.
> 2. Also on side bar, from my point of view I don't think if is necessary to add those icons located next to searching component to the header of sidebar, as the user he/she will click on sidebar icon to look for something new. I think is like duplicating things.
>    As usually, if I am wrong, please remember I am willing to hear from you.
>    Apart from that, you've done great work.

> Details

1. The issue with the size was resolved. If there is something specific about that, please send me a screenshot, or head over to chromatic and point it out.

2. That is just placeholder content. I just didn't want to leave it blank.

2023-04-14 09:04 UTC, musllim approved these changes
LGTM

2023-04-16 22:52 UTC, emilenfc approved these changes

2023-04-16 22:52 UTC, emilenfc approved these changes
LGTM

2023-04-19 08:22 UTC, mucyoalexaxel requested changes
@shyakadavis look into the suggested changes and address them ASAP.

2023-04-19 08:22 UTC, mucyoalexaxel commented on src/components/navbar/Categories.tsx
> +  if (!isHome) return null;
```suggestion
```
Wrap all this logic in a hook and import it in this file.

2023-04-19 08:22 UTC, mucyoalexaxel commented on src/components/navbar/Categories.tsx
> +      {/* BUTTON FOR SIDEBAR END HERE */}
```suggestion
```
Create external Components and import them, this will improve code readability.

2023-04-19 08:22 UTC, mucyoalexaxel commented on src/components/sidebar/SideBar.tsx
Refactor this file and use custom hooks.

2023-04-19 16:20 UTC, shyakadavis commented on src/components/sidebar/SideBar.tsx
Done. Please take a look.

2023-04-19 16:55 UTC, ISHIMWE-Aime commented
Good evening @shyakadavis , I like the way use addressed the changes requested by @alainmucyo , but I have noticed something remaining: 
If I am not wrong, you have use react custom hook as he suggested in sideBar.tsx file. 
If I am wrong, I am sorry and thank you.

2023-04-19 16:59 UTC, shyakadavis commented
> Good evening @shyakadavis , I like the way use addressed the changes requested by @alainmucyo , but I have noticed something remaining: If I am not wrong, you have use react custom hook as he suggested in sideBar.tsx file. If I am wrong, I am sorry and thank you.

I don't know how I missed that. Thanks.

2023-04-19 20:15 UTC, SergeInGithub approved these changes
LGTM

2023-04-19 21:08 UTC, emilenfc approved these changes

2023-04-19 21:09 UTC, musllim approved these changes
LGTM

2023-04-19 21:36 UTC, ISHIMWE-Aime approved these changes
LGTM

2023-04-19 22:00 UTC, mucyoalexaxel approved these changes
Great Work @shyakadavis

2023-04-19 22:01 UTC, merged