ft: add parent/generic parent modal component 📻
atlp-rwanda/e-comm-team-axel25-fe pull request #52
Opened 2023-04-07 13:59 UTC by shyakadavis

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-08 16:07 UTC, SergeInGithub reviewed
Nice work here. 
Some ui suggestions though, i think the design could do with some improvement, mostly the close button, i think if it would just be the `X` icon without the border it'd look better

2023-04-08 16:10 UTC, SergeInGithub commented
> Nice work here.
> Some ui suggestions though, i think the design could do with some improvement, mostly the close button, i think if it would just be the `X` icon without the border it'd look better

2023-04-08 16:22 UTC, SergeInGithub reviewed
Something else, I also noticed that `autodocs` on storybook aren't working properly for both the navbar or this component, maybe you should fix it or remove it since you already provide the `default` story

2023-04-09 11:27 UTC, emilenfc submitted a review, later dismissed
Nice work

2023-04-11 16:58 UTC, SergeInGithub approved these changes
LGTM

2023-04-14 09:11 UTC, musllim approved these changes
LGTM

2023-04-19 08:05 UTC, mucyoalexaxel submitted a review, later dismissed
Great Work

2023-04-19 17:02 UTC, ISHIMWE-Aime submitted a review, later dismissed
LGTM

2023-04-19 19:59 UTC, mucyoalexaxel requested changes
@shyakadavis Review Requested changes

2023-04-19 19:59 UTC, mucyoalexaxel commented on src/components/shared/modals/Modal.tsx
> +  if (!isOpen) return null;
```suggestion
```

@shyakadavis Wrap all that logic into a custom hook,.

2023-04-19 22:53 UTC, mucyoalexaxel requested changes
@shyakadavis Great Work here, Check some suggested change below

2023-04-19 22:53 UTC, mucyoalexaxel commented on src/components/shared/modals/Modal.tsx
> +  );
```suggestion
```
@shyakadavis Refactor this as well

2023-04-19 23:36 UTC, mucyoalexaxel approved these changes
Great Job @shyakadavis

2023-04-19 23:37 UTC, merged