#184749809 chore:setup git action
atlp-rwanda/e-comm-team-axel25-fe pull request #6
Opened 2023-03-22 10:27 UTC by emilenfc

# Description
add: setup of git action
## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-22 11:37 UTC, SergeInGithub requested changes
Check the change i suggested

2023-03-22 11:37 UTC, SergeInGithub commented on .github/workflows/index.yml
> +        run: npm run build
We are using pnpm
```suggestion
        run: pnpm install

      - name: Build application
        run: pnpm run build
```

2023-03-22 11:42 UTC, SergeInGithub approved these changes
LGTM

2023-03-22 11:58 UTC, shyakadavis requested changes
Is there a specific reason why you are pushing the `build` folder, if not, you need to add `build` in the gitignore because it shouldn't be pushed.

The deployment service is the one which builds, and uses that folder.

I don't think we need it.

2023-03-22 12:17 UTC, shyakadavis approved these changes
LGMT 🚀

2023-03-22 12:29 UTC, SergeInGithub approved these changes
LGTM

2023-03-22 20:23 UTC, mucyoalexaxel requested changes

2023-03-23 03:51 UTC, mucyoalexaxel approved these changes
LGTM

2023-03-23 03:52 UTC, merged