ft user view and edit profile
atlp-rwanda/e-comm-team-axel25-fe pull request #73
Opened 2023-04-25 14:40 UTC by emilenfc

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-08 16:06 UTC, mucyoalexaxel requested changes
@emilenfc Check suggestions below

2023-05-08 16:06 UTC, mucyoalexaxel commented on src/features/profile/index.ts
@emilenfc Delete this file

2023-05-08 16:06 UTC, mucyoalexaxel commented on src/features/profile/sevices/GetUser.tsx
@emilenfc Why this ?

2023-05-08 16:49 UTC, emilenfc commented on src/features/profile/sevices/GetUser.tsx
I didn't use it

2023-05-08 19:20 UTC, shyakadavis commented
I am trying to update the profile of  a user and this is what I am getting.

<img width="510" alt="Screenshot 2023-05-08 at 21 19 21" src="https://user-images.githubusercontent.com/87414827/236913391-bf2de734-1794-4ebc-9845-786e4715b582.png">

2023-05-08 19:20 UTC, shyakadavis commented
What is wrong @emilenfc ?

2023-05-09 07:32 UTC, musllim submitted a review, later dismissed
LGTM

2023-05-09 10:08 UTC, musllim approved these changes
LGTM

2023-05-09 14:49 UTC, mucyoalexaxel approved these changes

2023-05-09 14:49 UTC, merged